services:
  backend_service:
    container_name: backend-container
    build: .
    ports:
      - 3080:3080 #LOCAL_PORT:CONTAINER_PORT
    platform: linux/x86_64
    working_dir: /backend-container
    volumes:
      - .:/backend-container
    depends_on:
      db_service:
        condition: service_healthy
    environment:
      - SERVER_PORT=3080
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
    restart: 'always'
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3080']
      timeout: 10s
      retries: 5
    networks:
      - virtual-network-1
  db_service:
    image: mysql:8.0.35
    container_name: db-container
    platform: linux/x86_64
    ports:
      - 3081:3306 #LOCAL_PORT:CONTAINER_PORT
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    networks:
      - virtual-network-1
volumes:
  db_data:
networks:
  virtual-network-1:
